apiVersion: v1
kind: Secret
metadata:
    name: dbsecret
type: Opaque
data:
        DB_USER_NAME: Y3RnZGV2b3Bz
        DB_NAME: Y3RnX2Rldm9wc19rdHJhY2tlcg==
        DB_PASSWORD: ZGV2b3BzMTIz
        DB_HOST: ZGV2b3BzLWNhcGFiaWxpdHktdHJhY2tlci5jbXJrdnhwYjV6aWwudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t