# write kubernetes manifest file for deployment and service  
# Path: sample-python-app-lmt\k8s\deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app-lmt
  labels:
    app: sample-python-app-lmt
spec:

    replicas: 2
    selector:
        matchLabels:
          app: sample-python-app-lmt
    template:
        metadata:
          labels:
              admission.datadoghq.com/enabled: "true"
              app: sample-python-app-lmt
              logFileName: app
          annotations:
            admission.datadoghq.com/python-lib.version: v1.17.1
            
        spec:
          containers:
            - name: sample-python-app-lmt
              image: ghcr.io/cybage-devops/sample-python-app-lmt:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 5000
              env:
                - name: LOG_LEVEL
                  value: "INFO"
                - name: LOG_FILE
                  value: "/var/log/app.log"
                - name: MY_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: MY_POD_SERVICE_ACCOUNT
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.serviceAccountName
                - name: DB_USER_NAME
                  valueFrom:
                      secretKeyRef:
                        name: dbsecret
                        key: DB_USER_NAME
                - name: DB_NAME
                  valueFrom:
                      secretKeyRef:
                        name: dbsecret
                        key: DB_NAME
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: dbsecret
                        key: DB_PASSWORD
                - name: DB_HOST
                  valueFrom:
                      secretKeyRef:
                        name: dbsecret
                        key: DB_HOST                        
              volumeMounts:
                - name: log-volume
                  mountPath: /var/log
              resources:
                requests:
                  memory: "100Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"    
          imagePullSecrets:
            - name: dockerconfigjson-github-com
          volumes:
            - name: log-volume
              emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sample-python-app-lmt
spec:

    selector:
        app: sample-python-app-lmt
    ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
    type: NodePort


