  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: python-java-ingress
  spec:
    ingressClassName: nginx
    rules:
      - http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: sample-python-app-lmt
                  port:
                    number: 5000
              path: /test
            - pathType: Prefix
              backend:
                service:
                  name: sample-python-app-lmt
                  port:
                    number: 5000
              path: /metrics
             - pathType: Prefix
              backend:
                service:
                  name: sample-java-app-lmt
                  port:
                    number: 8085
              path: /
