
# write kubernetes manifest file for ingress
# Path: sample-python-app-lmt\k8s\ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-python-app-lmt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
    rules:
    - host: sample-python-app-lmt.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
                name: sample-python-app-lmt
                port:
                  number: 5000
