apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::465340416678:role/eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters  
      rolearn: arn:aws:iam::465340416678:role/OIDCRole 
      username: oidc-provider
  mapUsers: |
    - userarn: arn:aws:iam::465340416678:user/tanaji 
      username: tanaji
      groups:
        - system:masters