apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::465340416678:role/eks-node-group
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:master  
      rolearn: arn:aws:iam::465340416678:role/OIDCRole 
      username: oidc-provider
  mapUsers: |
    - userarn: arn:aws:iam::465340416678:user/tanaji 
      username: tanaji
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-08T05:15:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "962"
  uid: 50f8a309-bc73-4160-8c03-a2d180eca128
