name: Docker Image CI

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sample-python-app-lmt:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
             docker build . --file Dockerfile --tag sample-python-app-lmt:latest
             docker tag sample-python-app-lmt:latest ghcr.io/cybage-devops/sample-python-app-lmt:latest
             docker push ghcr.io/cybage-devops/sample-python-app-lmt:latest

- name: loki-action
  # You may pin to the exact commit or the version.
  # uses: metrico/loki-action@51bb4d201cbd710b19773d7457d074f960b6bf3b
  uses: metrico/loki-action@v2
  with:
    # GitHub token to access repo data
    repo-token: 
    # Comma separated names of the jobs to collect logs from, defaults to all jobs
    job-names: build
    # logql API push endpoint
    endpoint: http://54.91.131.230:3000/
    # comma separated values pointing to logql endpoints
    #addresses: # optional
    # logql api username
    username: admin
    # logql api password
    password: ${{ secrets.LOGQL_PASS }}
    # optional partition id
  #  partition: # optional


