name: Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "feature1.0" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sample-python-app-lmt:feature:1.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
             docker build . --file Dockerfile --tag sample-python-app-lmt:feature:1.0
             docker tag sample-python-app-lmt:feature:1.0 ghcr.io/cybage-devops/sample-python-app-lmt:feature:1.0
             docker push ghcr.io/cybage-devops/sample-python-app-lmt:feature:1.0
